### ISSUE TITLE
Unhandled header!

### ISSUE THREAD

**Issue by Ri773r** [FGasper/zmodemjs#10]
I try to implement zmodem protocol using zmodemjs on websocket
And follow the zmodemjs documentation
But when I input rz and sz commands, I get an error. I do n’t know how to solve it.
Can you give me some suggestions or solutions?
Thank you

### Platform and software version
Ubuntu 18.04.3 LTS
lrzsz version 0.12.21rc

### Console error output
When running rz
![image](https://user-images.githubusercontent.com/44192396/75788175-d05c0c80-5da2-11ea-95f1-74029a21da6d.png)
When running sz
![image](https://user-images.githubusercontent.com/44192396/75788290-fbdef700-5da2-11ea-9308-dcb8530ad991.png)

This problem has troubled me for a long time
Thanks again

**Comment by FGasper** [comment]
Best advice I can offer is to refer to existing implementations (e.g., ttyd). There’s also an example sz CLI implementation in the repo.

**Comment by Ri773r** [comment]
The code implementation completely refers to the existing implementation, but it still reports an error  
Is this a back-end problem？

**Comment by FGasper** [comment]
Can you provide a test case that fails?

**Comment by Ri773r** [comment]
yes  
the test case in this [repository](https://github.com/Ri773r/Webterminal) can reproduce this situation  
you can enter rz and sz commands in the terminal  
then you will find the error in the console  
thanks

**Comment by FGasper** [comment]
Can you please rework that to a test case for this repository, some JS code that demonstrates how the library as it stands is behaving contrary to its documentation?

**Comment by Ri773r** [comment]
I found out why I didn't set the sender callback
I'm sorry
But then there's a new error. SZ sometimes returns an error
![image](https://user-images.githubusercontent.com/44192396/77822493-303d9d00-712e-11ea-83a5-f66895ccad1f.png)
Does this mean that I need to send "OO" after saving the file to disk
Like this
```javascript
Zmodem.Browser.save_to_disk(
xfer._spool,
xfer.get_details().name
)
that.ws.send(new Uint8Array([79, 79]))
```

**Comment by FGasper** [comment]
I’m closing this, as there hasn’t yet materialized a test case that shows a reproducible bug.

I do recognize that it’s hard to get use of this library correct. I’d also accept a PR to add examples of correct usage.

**Comment by Lvyc1995** [comment]
@walirt 你好，我遇到了和你一样得问题，请问你是怎么解决得呢？

**Comment by Lvyc1995** [comment]
@walirt Hello, I encountered the same problem as you, how did you solve it? Where do you mean to set the sender callback? How to solve the subsequent OO problem? Can you provide an simple example? thanks

**Comment by FGasper** [comment]
@Lvyc1995 https://github.com/FGasper/zmodemjs#troubleshooting

**Comment by Lvyc1995** [comment]
> @Lvyc1995 https://github.com/FGasper/zmodemjs#troubleshooting

thanks

**Comment by xiaowang04821** [comment]
@walirt Hi,I encountered the same problem as you, Have you solved it, I want to see your example,thanks.

**Comment by Lvyc1995** [comment]
建议参考一下这个项目，逻辑是一样的：https://github.com/huyuan1999/django-webssh

**Comment by hessonsu** [comment]
I have solved the problem!
copy for example
--------------------
let zsentry = new Zmodem.Sentry( {
    to_terminal(octets) { .. },  //i.e. send to the terminal

    sender(octets) { .. },  //i.e. send to the ZMODEM peer

    on_detect(detection) { .. },  //for when Sentry detects a new ZMODEM

    on_retract() { .. },  //for when Sentry retracts a Detection
} );
----------------------
modify code
sender(octets) { websocket.send(new Uint8Array(octets) }

**Comment by walirt** [comment]
> ## I have solved the problem!
> copy for example
> let zsentry = new Zmodem.Sentry( {
> to_terminal(octets) { .. }, //i.e. send to the terminal
> 
> ```
> sender(octets) { .. },  //i.e. send to the ZMODEM peer
> 
> on_detect(detection) { .. },  //for when Sentry detects a new ZMODEM
> 
> on_retract() { .. },  //for when Sentry retracts a Detection
> ```
> 
> ## } );
> modify code
> sender(octets) { websocket.send(new Uint8Array(octets) }

My code is the same as yours, but it still reports errors
`
Uncaught PROTOCOL: Only thing after ZFIN should be “OO” (79,79)
`

**Comment by Lvyc1995** [comment]
Your back-end code needs to process the'OO' code returned by the server. This process requires the cooperation of the front and back ends.You can refer to this project: https://github.com/huyuan 1999/django-webssh, the relevant logic in ssh.py
