### ISSUE TITLE
Xtermjs + ssh2 ，How to use zmodemjs？

### ISSUE THREAD

**Issue by funjobs** [FGasper/zmodemjs#18]
Can you provide some demos about zmodemjs?

**Comment by Lvyc1995** [comment]
+1

**Comment by FGasper** [comment]
@funjobs There’s demo usage in the distribution’s tests, and in old xtermjs versions there was a plugin.

If you want to contribute further demo code I’d be happy to look at it.

**Comment by funjobs** [comment]
Thanks.The documentation of zmodemjs may be a bit simple for me. I don't know how to use ssh2 with zmodemjs.

**Comment by FGasper** [comment]
@funjobs I’m not sure what SSH would have to do with it; WebSocket-powered terminals generally use TLS for encryption.

**Comment by leffss** [comment]
> Thanks.The documentation of zmodemjs may be a bit simple for me. I don't know how to use ssh2 with zmodemjs.

https://github.com/leffss/gowebssh
