### ISSUE TITLE
'Zmodem.Browser' is Undefined

### ISSUE THREAD

**Issue by xiaowang04821** [FGasper/zmodemjs#19]
When I tried to use zmodem.js in Vue Cli, I found this problem after writing according to your document. Then I went to look at the source code of zmodem.js/src/zessions.js in node_modules and found that you did not introduce'zmodem_browser.js'. I wonder if you did it intentionally?
- zmodem.js 0.1.10version

**Comment by FGasper** [comment]
It’s in the dist/ files but not included in lib/.

Feel free to submit a PR to add a separate lib/zmodem_browser.js that includes Zmodem.Browser.

**Comment by xiaowang04821** [comment]
> 它在dist /文件中，但不包含在lib /中。
> 
> 随时提交PR，以添加包含Zmodem.Browser的单独的lib / zmodem_browser.js。

Thank you very much. I have found the right way
