### ISSUE TITLE
when sz in linux, crc32 failed

### ISSUE THREAD

**Issue by yumaojun03** [FGasper/zmodemjs#3]
exception: 
```js
Uncaught Error: CRC check failed! (got: 97,49,55,32; expected: 99,203,3,169)
    at a (zmodem.js:1)
    at Object.verify32 (zmodem.js:1)
    at i (zmodem.js:1)
    at Function.parse (zmodem.js:1)
    at r.Session.Receive._parse_and_consume_header (zmodem.js:1)
    at r.Session.Receive._consume_first (zmodem.js:1)
    at r.Session.Receive.consume (zmodem.js:1)
    at t.Sentry.consume (zmodem.js:1)
    at WebSocket.handleWSMessage (zmodem.ts:75)
```

lrzsz version:
```js
sz (lrzsz) 0.12.21rc
```

but use sz -e is ok
```
sz -h
-e, --escape                escape all control characters (Z)
```

so, i think when your crc, include control charaters?

can you fix it.
Thank you~!~

**Comment by FGasper** [comment]
Hi, thanks for the bug report!

Can you please attach the file you were trying to send via sz and the sz command that you used to send the file? And, are you saying that the CRC check does work, or doesn’t work, with the `-e` flag?

(I mean, there’s not much point to the CRC check since it’s all over TCP anyway.)

**Comment by yumaojun03** [comment]
In my case,  i use xtermjs to connect my backend Linux server through websocekt,  xtermjs use this lib to implement zmodem

this my backend server distribution information:
```sh
root@xcpc:~# cat /etc/issue
Ubuntu 18.04.2 LTS \n \l
```

github can't attach file to issue,  i will record my operate below:

1. i touch a new file, nothing in it,  sz file a failed:
```sh
root@ecs-52a0:~/sz_test# touch a
root@ecs-52a0:~/sz_test# sz a
3445316036 100644 0 1 0kØ&M
```
in my browser's developer tool console:
```js
zmodem.js:1 Uncaught Error: CRC check failed! (got: 97,48,32,49; expected: 99,203,3,169)
    at a (zmodem.js:1)
    at Object.verify32 (zmodem.js:1)
    at i (zmodem.js:1)
    at Function.parse (zmodem.js:1)
    at r.Session.Receive._parse_and_consume_header (zmodem.js:1)
    at r.Session.Receive._consume_first (zmodem.js:1)
    at r.Session.Receive.consume (zmodem.js:1)
    at t.Sentry.consume (zmodem.js:1)
    at WebSocket.handleWSMessage (zmodem.ts:75)
```

2. but use sz -e can receive server a file success:
```sh
root@ecs-52a0:~/sz_test# sz -e a
**B00000000000000
```

in my browser developer tool console, has two exception, but file can receive success:
```js
zmodem.js:1 Uncaught ReferenceError: array_buf is not defined
    at r.Session.Receive._consume_first (zmodem.js:1)
    at r.Session.Receive.consume (zmodem.js:1)
    at t.Sentry.consume (zmodem.js:1)
    at WebSocket.handleWSMessage (zmodem.ts:75)

zmodem.js:1 Uncaught ReferenceError: array_buf is not defined
    at r.Session.Receive._consume_first (zmodem.js:1)
    at r.Session.Receive.consume (zmodem.js:1)
    at t.Sentry.consume (zmodem.js:1)
    at WebSocket.handleWSMessage (zmodem.ts:75)
```

**Comment by FGasper** [comment]
Thank you for this! I’ll have a look at this later.

Two other questions:

1) Does the same problem happen with lrzsz 0.12.20?

2) Does the xtermjs test suite pass on your machine, with lrzsz 0.12.21rc?

**Comment by FGasper** [comment]
I pushed a fix for the array_buf issue.

**Comment by FGasper** [comment]
Also, in your xtermjs installation, are you using binary or text WebSocket messages? (zmodemjs requires binary.)

**Comment by yumaojun03** [comment]
1.  same problem with lrzsz version is 0.12.21rc(on ubuntu18.04), not 0.12.20, i will test 0.12.20 later 

2. xtermjs demo for zmodem is pass, i can use sz send file success,  my mac book's lrzsz version is 0.12.20

i develop an proxy use golang,  which use ssh over websocket, It's a little different from demo.

**Comment by yumaojun03** [comment]
my proxy server transfer data with binary, not use text.

**Comment by FGasper** [comment]
I just tried Ubuntu 18.10’s lrzsz (which reports as version 0.12.21rc) against the test suite, and it passed.

If the demo works but your implementation doesn’t, then notwithstanding the `array_buf` bug, this sounds like it might be a problem in your implementation.

**Comment by yumaojun03** [comment]
ok, thanks, I'll check my implementation again.

**Comment by yumaojun03** [comment]
it's my problem,  i found,  it's ok now, thanks!!!

**Comment by FGasper** [comment]
@yumaojun03 As it happens, while digging into this I realized that there were no tests that actually flex the “happy path” in receive transfers. Worse, I realized that some of tests I did have failed reliably but weren’t even running because of a bug in another test.

So, I’ll roll fixes for all of these into a new release.
