### ISSUE TITLE
Having trouble in cancel a upload process

### ISSUE THREAD

**Issue by zxdong262** [FGasper/zmodemjs#4]
Hi @FGasper 
Thank you for your great work, 

I am trying to add Zmodem support to [electerm](https://github.com/electerm/electerm), I can manage to upload/download/cancel download, but can not cancel the upload, can you give example of cancel download?

**Comment by FGasper** [comment]
To be honest, I’m not sure that that’s possible in zmodem. I don’t see anything in the protocol documentation about it.

What does sz do if it receives SIGINT while sending the file?

**Comment by zxdong262** [comment]
@FGasper Thank you, but I do not know sz process detail.

**Comment by azuoge** [comment]
Hi @FGasper 
Thank you for your great work
I am trying to add Zmodem support to xterm, can you give example of cancel upload？

**Comment by FGasper** [comment]
@azuoge Look in xterm.js’s repository history for a plugin that I contributed a couple years ago but is incompatible with their new plugin API.
