### ISSUE TITLE
Ready enough for general usage?

### ISSUE THREAD

**Issue by NuSkooler** [FGasper/zmodemjs#6]
I'd love to include a "native" Z-Modem in [ENiGMA 1/2 BBS](https://github.com/NuSkooler/enigma-bbs) - is this ready for general-ish use?

**Comment by FGasper** [comment]
@NuSkooler It’s as ready as it’s likely to be for the foreseeable future. I myself don’t use it anymore, and the original xterm.js integration that I wrote is incompatible with that project’s new plugin system, but there are other integrations into, e.g., electerm and ttyd, and I continue to support zmodem.js when issues have arisen—which has been rare. The source tree now includes a CLI replacement for sz, if you want to try it out. (A similar replacement for rz would not be difficult to write.)

Do note that this code makes a number of assumptions about its environment that other, older zmodem implementations don’t make; most prominently, a reliable transport is assumed, and no error-checking is done. See the docs for more details.

**Comment by NuSkooler** [comment]
@FGasper Perfect, thanks for the response! I may give this a go soon when I can find some free time. The BBS software in question is only over TCP/IP so should generally be fine.
