### ISSUE TITLE
xterm.js v4 and zmodem.js

### ISSUE THREAD

**Issue by jerch** [FGasper/zmodemjs#7]
@FGasper 

Imho zmodem was a valuable addon for xterm.js, but got removed with v4 due changes on our side. Do you have any plans to reestablish such an addon?

Just want to let you know that I might do an addon myself in case you dont want to maintain it yourself.

**Comment by FGasper** [comment]
Please feel free.

While I still maintain this library, I’ve actually not had the use for the plugin that I anticipated.

Let me know how it goes; I’ll be happy to link to it.

**Comment by x-077** [comment]
Hello @jerch , 

I know its an old issue but I was wondering if you have a chance to publish your addon for xterm.js / zmodem  ? 

Thanks
